### PR TITLE
Post subscription

### PR DESCRIPTION
**Pull request by dexfs**

### CODE REVIEW

**Comment by dexfs** [comment]
@jgcmarins @gsasouza 

To reproduce it's necessary to run https://github.com/dexfs/entria-challenge, I don't know why but  subscription isn't working on heroku.

**Comment by jgcmarins** [comment]
do you have any log with error messages?

**Comment by jgcmarins** [comment]
maybe it's missing a few configs

**Comment by dexfs** [comment]
@jgcmarins I'll get it at night and I'll post here.

**Comment by dexfs** [comment]
screen shot 2018-05-08 at 20 43 47

@jgcmarins I found out the problem it's because the browsers not accept insecure connection in this case ws://, so, it's a paid resource on heroku.

**Comment by jgcmarins** [comment]
nice debug

**Pull request merged**
